### ISSUE TITLE
Todays graph shows the wrong data

### ISSUE THREAD

**Issue by TheArcturian** [Danielhiversen/home_assistant_tibber_custom#14]
Hi. It seems like todays graph is showing the wrong data. For instance, the graph says "0.45 at 14:00", but in reality (and in the Tibber app) it is "0.14 øre" at that time.

Also the consumption isn't updated since a few hours before midnight.

![StuckGraph](https://user-images.githubusercontent.com/16746633/113395047-8ffe0200-9399-11eb-90eb-4e3094c97853.JPG)

**Comment by joffaHA** [comment]
Same issue. The entity has not been updated in the last 4 or 5 days
