### ISSUE TITLE
Consumtion not shown

### ISSUE THREAD

**Issue by wackerr** [Danielhiversen/home_assistant_tibber_custom#18]
Hi,
Got tibber_custom configured and correctly shows todays pricing.
I also have Tibber pulse and get my consumption into HA but it is now shown on the graph/camera.
Is there anything I need to do to get it to show?

**Comment by Danielhiversen** [comment]
Modify this line to match your realtime sensor
https://github.com/Danielhiversen/home_assistant_tibber_custom/blob/main/custom_components/tibber_custom/camera.py#L57

**Comment by tore1980** [comment]
@Danielhiversen What is the correct modification im using tibber, like this:  f"sensor.real_time_consumption_{slugify(self.sensor.power_address_5)}"

Sensor name: sensor.power_address_5
