### ISSUE TITLE
Missing camera.YOUR_ADRRESS

### ISSUE THREAD

**Issue by janegilring** [Danielhiversen/home_assistant_tibber_custom#23]
I have installed and configured the Tibber integration, and have 2 devices and 41 entities from the integration. These are spread across two different locations (home and the cabin).

I then added this repository as a custom repository in HACS, and finally added the following in configuration.yaml:
tibber_custom:

However, after restarting Home Assistant, I can`t find any entity named camera.YOUR_ADRRESS.

Could this be due to the fact that two locations is available in the Tibber account? Or should the integration handle that and simply add one camera per address?

**Comment by langtind** [comment]
I have two locations in Tibber, and both are available in Home Assistant. 
camera.address1
camera.address2

**Comment by janegilring** [comment]
Great, thanks.

Are there any specific log I could look into to determine why the entities are missing?

**Comment by kongjudas** [comment]
I had it running smoothly until it suddenly disappeared today, after a reboot. The only change from my side was on the Recorder. There's nothing in the log other than:
`2021-12-22 23:41:09 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration tibber_custom which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
`

**Comment by boheme61** [comment]
> Great, thanks.
> 
> Are there any specific log I could look into to determine why the entities are missing?

If you "solved this" please close it

**Comment by janegilring** [comment]
I had this on the last line in configuration.yaml:
tibber_custom:

After adding a new line beneath and restarting HA, the camera entities showed up.

**Comment by jovana** [comment]
> 

Thanks for this tip! Same issue here, give a new line below the tibber_custom: and restarted, it gives the camera option.
