### ISSUE TITLE
camera.YOUR_ADRRESS does not have a unique ID

### ISSUE THREAD

**Issue by thunem** [Danielhiversen/home_assistant_tibber_custom#24]
This entity ('camera.r_xxxxxxx14') does not have a unique ID, therefore its settings cannot be managed from the UI

Anyone know how to solve this? I've tried to remove tibber_custom, restarted HA and reinstalled tibber_custom without any luck.

**Comment by Danielhiversen** [comment]
The integration does not support a unique ID
