### ISSUE TITLE
Missing support for width and height

### ISSUE THREAD

**Issue by postlund** [Danielhiversen/home_assistant_tibber_custom#26]
I get this message in the log now:

    The camera entity camera.xxx does not support requesting width and height, please open an issue with the integration author

Just wanted to make notice of it.

**Comment by boheme61** [comment]
> I get this message in the log now:
> 
> ```
> The camera entity camera.xxx does not support requesting width and height, please open an issue with the integration author
> ```
> 
> Just wanted to make notice of it.

You still get this "Message" ?

**Comment by Danielhiversen** [comment]
Fixed in 0.5
