### ISSUE TITLE
Feature request: provide raw data

### ISSUE THREAD

**Issue by umrath** [Danielhiversen/home_assistant_tibber_custom#30]
While this integration is great to provide a graph where I can see whether the costs go up or down, I cannot use it for any kind of automation.
The original Tibber integration does not provide data for the next day either.

Is there a way to make the data points available to consume in automations?

**Comment by Danielhiversen** [comment]
No plans for that.
It is available from Python with `hass.data["tibber"]`
https://github.com/Danielhiversen/home_assistant_tibber_custom/blob/main/custom_components/tibber_custom/camera.py#L20
