### ISSUE TITLE
Possibly broken with 2022.5

### ISSUE THREAD

**Issue by camelen** [Danielhiversen/home_assistant_tibber_custom#32]
I get the following error:

Logger: homeassistant.setup
Source: setup.py:298 
First occurred: 10:13:34 PM (1 occurrences) 
Last logged: 10:13:34 PM

Unable to prepare setup for platform tibber_custom.camera: Platform not found (numpy.core.multiarray failed to import).

While I haven’t changed any of my configs. Just updated to 2022.5.

Is it working for anyone else on this version?

**Comment by Benmjol** [comment]
Same problem for me since upgrading

**Comment by SebSkarp** [comment]
Yup the exact same thing happened to me too.

**Comment by ChristopherSathen** [comment]
Same here.

**Comment by henrikeri** [comment]
Same issue and error message here

**Comment by pertakman** [comment]
Works for me again with 2022.5.2.

**Comment by henrikeri** [comment]
Same! Guess this can be closed

**Comment by camelen** [comment]
Yep. It works with the latest update.

**Comment by boheme61** [comment]
yep, works now
