### ISSUE TITLE
How to rename/name the tibber energy sensor?

### ISSUE THREAD

**Issue by linust** [Danielhiversen/home_assistant_tibber_custom#33]
How can I change (or re-setup) the tibber energy sensor with a sensible and short name?

Right now I have something like this in the energy dashboard
tibber:energy_consumption_783b7040e25640d097xxxxxxxx12456

Would prefer something like tibber:total_consumption (that fits the UI)

**Comment by Danielhiversen** [comment]
No relevant for this custom component

**Comment by linust** [comment]
Thanks for a great integration/service 

I partly understand the conclusion. If there is a way to influence the sensor name when setting up the Tibber integration, then it seems like a rename of a (historical) entity should be a core feature.

Is there a way to influence the name of the Tibber total consumption entity when setting up the integration? 

(If so it'll solve my problem since I can remove the integration and redo the setup).

**Comment by linust** [comment]
Now i noticed I ended up on the old custom component and not the standard one. I'll repost my request/issue there.
