### ISSUE TITLE
0.5 seem to break update of camera image

### ISSUE THREAD

**Issue by Rittsel** [Danielhiversen/home_assistant_tibber_custom#35]
I've not succeeded to get any debug logs out for this - but after upgrading to 0.5 I can still see a camera image in the widget - but it's always the same, have been for days - I just downgraded to 0.4 and now it's up to date again with today's pricing.

It was my guess from the beginning but I manually implemented the step based plot and that works fine - so something with the async_camera_image made it stop working for me.

**Comment by DeVille70** [comment]
I have the same issue - image stopped updating with 0.5.

**Comment by Rittsel** [comment]
Good to see I'm not alone - @postlund was this behaving differently for you in development?

**Comment by postlund** [comment]
@Rittsel No, not for me. I'm running the latest and greatest of everything and it works as expected for me.

**Comment by Rittsel** [comment]
> 

Thanks for confirming @postlund - interesting. I've also always been running latest and greatest of everything. I updated to 0.5 again and same issue still happening - I was hoping for some change since several minor releases of HA have happened as well.

Is it because of card config?

camera_view: live
type: picture-glance
title: Elpris
entities: []
camera_image: camera.tibber

Realized I forgot to include valuable information, but running latest

Home Assistant 2022.7.7
Supervisor 2022.07.0
Frontend-version: 20220707.1 - latest

**Comment by ErikThorsell** [comment]
I just downloaded the repository via HACS and used the same card config you (@Rittsel) shared above. Works as expected.

```
Version               | core-2022.7.7
Host Operating System | Home Assistant OS 8.4
Supervisor Version    | supervisor-2022.07.0
```

**Comment by erijo** [comment]
Have your tried 0.5.1 to see if that fixes it?

**Comment by Rittsel** [comment]
Yeah, I did several downgrades & upgrades and always the same result for me with 0.5 - but after upgrading to 0.5.1 it works again! Closing this

**Comment by DeVille70** [comment]
Yep, 0.5.1 works for me, as well. Thanks.
