### ISSUE TITLE
Failed logins from 127.0.0.1

### ISSUE THREAD

**Issue by ErikThorsell** [Danielhiversen/home_assistant_tibber_custom#36]
I downloaded v0.5 via HACS and installed on:

```
Home Assistant 2022.7.7
Supervisor 2022.07.0
Operating System 8.4
Frontend 20220707.1 - latest 
```

After a while, HA notified me about failed logins from 127.0.0.1. I had never seen that message before so I uninstalled the addon and now I have not seen the notification for hours; leading me to believe something in the addon is causing the notifications.

Anyone else seeing this? Maybe you can explain why.

**Comment by Danielhiversen** [comment]
Do not think it is related to this integration
