### ISSUE TITLE
Feature request 

### ISSUE THREAD

**Issue by johanschelin** [Danielhiversen/home_assistant_tibber_custom#39]
Is it possible to add functionality to read the value of sold electricity as well as bought in local currency?

**Comment by erijo** [comment]
I have a branch to add this to the tibber integration: https://github.com/erijo/home-assistant/tree/production

Just need to fix a test and possible some docs.

**Comment by johanschelin** [comment]
Excellent!
I’ll be happy to test if needed

Hämta Outlook för iOS<https://aka.ms/o0ukef>
________________________________
Från: Erik Flodin ***@***.***>
Skickat: Tuesday, August 2, 2022 8:01:32 PM
Till: Danielhiversen/home_assistant_tibber_custom ***@***.***>
Kopia: Johan Schelin ***@***.***>; Author ***@***.***>
Ämne: Re: [Danielhiversen/home_assistant_tibber_custom] Feature request (Issue #39)


I have a branch to add this to the tibber integration: https://github.com/erijo/home-assistant/tree/production

Just need to fix a test and possible some docs.

**Comment by erijo** [comment]
PR-link for reference: home-assistant/core#76165.
