### ISSUE TITLE
[Enhancement] Add support for external energy meters

### ISSUE THREAD

**Issue by fn87** [Danielhiversen/home_assistant_tibber_custom#4]
I have Tibber but no Pulse or Watty. I do have is an home built energy meter that provide real time information.

A possible enhancement would be that a sensor could be provided for the hourly consumption to replace the once from Tibber.

**Comment by Danielhiversen** [comment]
Thanks for your suggestion. But the component depends on specific data from the Tibber component, so I do not plan to extend it to external sensors.
