### ISSUE TITLE
Error when adding custom repository

### ISSUE THREAD

**Issue by pe22ad** [Danielhiversen/home_assistant_tibber_custom#41]
Hi, 

I try to add this to the Custom repositories as instructed as described in the installation instruction. I'm getting an error messages that says "<Plugin Danielhiversen/home_assistant_tibber_custom> Repository structure for 0.5.1 is not compliant" 

What is the problem?

//Per

**Comment by oyta** [comment]
@pe22ad  You probably need to choose "Integration" and not "Lovelace". At least that worked for me. 

Please respond whether it works for you or not, so that the issue can be closed.

**Comment by pe22ad** [comment]
My misstake, now it works! Thanks!

**Comment by oyta** [comment]
I guess this issue can be closed now, @Danielhiversen
