### ISSUE TITLE
Electricity Price two hours old, should be current price

### ISSUE THREAD

**Issue by HAPSagan** [Danielhiversen/home_assistant_tibber_custom#45]
The Tibber integration shows a two-hour old value for the current price.
I have found two Issues that are closed on this topic, without finding what to do. I have tried removing and adding the integration with no difference. I have Core 10.5 installed and this has not helped either.

Electricity Price two hours old, should be current price #80603

Tibber integration seems to report the wrong price since 2022.10.0 #79701

**Comment by RH-Dreambox** [comment]
Same problem here, the time-price is not the same as in mobile app.
