### ISSUE TITLE
Feature Request - Future Data in a sensor entity

### ISSUE THREAD

**Issue by dickesW** [Danielhiversen/home_assistant_tibber_custom#46]
Hi @Danielhiversen,

thank you for the nice integration and your work.

As you already use the data which is stored in HA by the offical tibber integration it would be very nice to put this future data into a new sensor - in the same format the nordpool intergration does. So it would be possible to use all the templates which are out there in the community to find the cheapest hours without creating a new rest sensor to pull the data from the tibber API again.

Thanks dickesW

**Comment by Danielhiversen** [comment]
https://github.com/Danielhiversen/home_assistant_tibber_data/pull/34
