### ISSUE TITLE
What to expect from this?

### ISSUE THREAD

**Issue by palengh** [Danielhiversen/home_assistant_tibber_custom#5]
Hi, Daniel!
You do a great job with AI, Tibber and Easee. Appreciate it!

I was gonna test this add-on, and has installed it through HACS, and was prompted for an update today to versjon 0.2.
I do have the Tibber integration running, and Pulse is reporting values.

What would I expect from the timber_custom integration?
This is in my configuration.yaml, but nothing seems to show in regard to new sensors or whatever I would expect...

```
tibber:
  access_token: !secret tibber_access_token
tibber_custom:
```

**Comment by Danielhiversen** [comment]
Hei

You should find a `camera.YOUR_ADRRESS` entity that displays the current graphic.

**Comment by palengh** [comment]
Thank you!

![image](https://user-images.githubusercontent.com/12332161/101469211-bdcfbe80-3944-11eb-9d8e-93014d969bc4.jpeg)
