### ISSUE TITLE
Cant find image

### ISSUE THREAD

**Issue by FSHelgeland** [Danielhiversen/home_assistant_tibber_custom#51]
Installed through Hacs, made a restart, then added tibber_custom: to my config.yaml. Had another restart and get the error: 

`Logger: homeassistant.components.local_file.camera
Source: components/local_file/camera.py:78
Integration: local_file (documentation, issues)
First occurred: 23:48:34 (1 occurrences)
Last logged: 23:48:34

Could not read camera Hjemme image from file: /config/www/prices_Hjemme.png`

I have checked the www folder as well, and I cant find the image there. Where do I go wrong?

**Comment by FSHelgeland** [comment]
Tried everything but still de same. Removed Tibber, Tibber Data, and Tibber Custom. Removed every hints of them in config yaml. Restarted, and tried to add Tibber again from scratch, That was not possible as I got Unknown error already when pasting my access token. Then I had to restore my HA instance from backup, Tibber and Tibber Data runs fine, installed Tibber Custom again, and updated the config.yaml with tibber_custom: But it will still not draw the image, and I get the same error. But of course it is impossible to read an image that has not been created. This really frustrates me, og Daniel er jo sikkert på ferie. 

Well I never give up but this seems somehow to be very difficult.

**Comment by Romero-KCBS2003** [comment]
Today the camera pic is back at my Dashboard. I dont know, if the fix it or what my problem solved

**Comment by FSHelgeland** [comment]
Well I have still not managed to fix this

**Comment by FSHelgeland** [comment]
Well now there actually is a picture in the www.folder its 80x80, Hard to see anything at all

**Comment by FSHelgeland** [comment]
![image](https://github.com/Danielhiversen/home_assistant_tibber_custom/assets/93429993/96bbdaea-a3a8-4d90-b62c-6bc2066cb019)

**Comment by FSHelgeland** [comment]
And finally it works, reinstalled and downgraded to 0.5 not sure if it had anything to do with it, but now it is ok.
