### ISSUE TITLE
Does not work with new Home Assistant version

### ISSUE THREAD

**Issue by NebuDa** [Danielhiversen/home_assistant_tibber_custom#54]
I have installed the new hassio verdion and Matplotlib makes trouble, see my log below.

` 2024-02-08 06:48:11.431 ERROR (MainThread) [tibber.realtime] Watchdog: Connection is down, 2024-02-08 06:48:21.431156
2024-02-08 06:48:13.615 ERROR (SyncWorker_13) [homeassistant.util.package] Unable to install package matplotlib: error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [579 lines of output]
      
      Edit mplsetup.cfg to change the build options; suppress output with --quiet.
      
      BUILDING MATPLOTLIB
            python: yes [3.12.1 (main, Jan  4 2024, 11:43:50) [GCC 13.2.1 20231014]]
          platform: yes [linux]
             tests: no  [skipping due to configuration]
            macosx: no  [Mac OS-X only]
      
      /usr/local/lib/python3.12/site-packages/setuptools/__init__.py:80: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
      !!
      
              ********************************************************************************
              Requirements should be satisfied by a PEP 517 installer.
              If you are using pip, you can try `pip install --use-pep517`.
              ********************************************************************************
      
      !!
        dist.fetch_build_eggs(dist.setup_requires)
      [02/08/24 06:48:01] WARNING  toml section missing        pyproject_reading.py:42
                                   'pyproject.toml does not
                                   contain a
                                   tool.setuptools_scm
                                   section'
      /tmp/pip-install-wflcc07n/matplotlib_42a85b50ef564c63b6d343d4b40e7579/.eggs/setuptools_scm-8.0.4-py3.12.egg/setuptools_scm/git.py:308: UserWarning: git archive did not support describe output
        warnings.warn("git archive did not support describe output")
      /tmp/pip-install-wflcc07n/matplotlib_42a85b50ef564c63b6d343d4b40e7579/.eggs/setuptools_scm-8.0.4-py3.12.egg/setuptools_scm/git.py:327: UserWarning: unprocessed git archival found (no export subst applied)
        warnings.warn("unprocessed git archival found (no export subst applied)")
      /usr/local/lib/python3.12/site-packages/setuptools/dist.py:674: SetuptoolsDeprecationWarning: The namespace_packages parameter is deprecated.
      !!
      
              ********************************************************************************
              Please replace its usage with implicit namespaces (PEP 420).
      
              See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages for details.
              ********************************************************************************
      
      !!
        ep.load()(self, ep.name, value)
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-aarch64-cpython-312
      copying lib/pylab.py -> build/lib.linux-aarch64-cpython-312
      creating build/lib.linux-aarch64-cpython-312/mpl_toolkits
      copying  `

**Comment by JSoko** [comment]
Known issue:
https://github.com/Danielhiversen/home_assistant_tibber_custom/issues/53
