### ISSUE TITLE
tibber_custom integration no longer working after core update to 2024.2.1

### ISSUE THREAD

**Issue by padlefot** [Danielhiversen/home_assistant_tibber_custom#55]
Seeing this in the logs:

Setup failed for custom integration 'tibber_custom': Requirements for tibber_custom not found: ['matplotlib'].

the camera entitiy is no longer available.

**Comment by yutani42** [comment]
duplicate of #53

**Comment by padlefot** [comment]
yes sorry, I should have been more vigilant
