### ISSUE TITLE
Bug or intended in the columns?

### ISSUE THREAD

**Issue by TheArcturian** [Danielhiversen/home_assistant_tibber_custom#9]
Innimellom så blir de grå søylene feil. Dvs. søylen for aktuell time jeg ser på er veldig høy mens alle de tidligere søylene er små. Er det en bug eller er det noe den er ment å illustrere?

![TibberCustom](https://user-images.githubusercontent.com/16746633/107694471-b8c61d00-6caf-11eb-83d0-0bafbf8e0835.png)

I tillegg, hva er det numrene på høyresiden egentlig viser? De fra - 0 til - 250.

**Comment by Danielhiversen** [comment]
Probably a bug in calculating the consumption for the current hour.

**Comment by TheArcturian** [comment]
Ok. It happens now and then during the day.
Any info on what the numbers on the right side is?

**Comment by Danielhiversen** [comment]
kWh

**Comment by Danielhiversen** [comment]
Should be fixed by: https://github.com/Danielhiversen/home_assistant_tibber_custom/pull/13

**Comment by TheArcturian** [comment]
Great, thanks!
